/-
Copyright (c) 2026 IEANTN contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Terence Tao
-/
import IEANTN.Nodes.GammaAsymptotics.v2.Conclusions

/-!
# Challenge: `GammaAsymptotics.v2`

**Generated file - do not edit.**  Regenerated by
`python scripts/ieantn.py gen-challenges` from `Conclusions.lean` and
`formalization.yaml`; CI diffs the two.

Each `sorry` below is deliberate and permanent: a challenge *states*, it does not prove.
How each conclusion is justified is recorded in `formalization.yaml`, not here.
-/

theorem GammaAsymptotics.v2.challenge_digamma_sub_log_isBigO_strip : GammaAsymptotics.v2.digamma_sub_log_isBigO_strip := by
  sorry
