/-
Copyright (c) 2026 IEANTN contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Terence Tao
-/
import IEANTN.Nodes.KadiriLumley.v1.Conclusions

/-!
# Challenge: `KadiriLumley.v1`

**Generated file - do not edit.**  Regenerated by
`python scripts/ieantn.py gen-challenges` from `Conclusions.lean` and
`formalization.yaml`; CI diffs the two.

Each `sorry` below is deliberate and permanent: a challenge *states*, it does not prove.
How each conclusion is justified is recorded in `formalization.yaml`, not here.
-/

theorem KadiriLumley.v1.challenge_prime_in_interval_above_exp_59 : KadiriLumley.v1.prime_in_interval_above_exp_59 := by
  sorry

theorem KadiriLumley.v1.challenge_prime_in_interval_above_exp_60 : KadiriLumley.v1.prime_in_interval_above_exp_60 := by
  sorry
