/-
Copyright (c) 2026 IEANTN contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Sebastian Rodrigo
-/
import IEANTN.Nodes.PrimeInterval.v1.Conclusions

/-!
# Challenge: `PrimeInterval.v1`

**Generated file - do not edit.**  Regenerated by
`python scripts/ieantn.py gen-challenges` from `Conclusions.lean` and
`formalization.yaml`; CI diffs the two.

Each `sorry` below is deliberate and permanent: a challenge *states*, it does not prove.
How each conclusion is justified is recorded in `formalization.yaml`, not here.
-/

theorem PrimeInterval.v1.challenge_theta_characterisation : PrimeInterval.v1.theta_characterisation := by
  sorry

theorem PrimeInterval.v1.challenge_eTheta_criterion : PrimeInterval.v1.eTheta_criterion := by
  sorry

theorem PrimeInterval.v1.challenge_numericalBound_hasPrimeInInterval : PrimeInterval.v1.numericalBound_hasPrimeInInterval := by
  sorry

theorem PrimeInterval.v1.challenge_classicalBound_hasPrimeInInterval : PrimeInterval.v1.classicalBound_hasPrimeInInterval := by
  sorry
