/-
Copyright (c) 2026 IEANTN contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Terence Tao
-/
import IEANTN.Nodes.ZetaZeroes.v1.Conclusions

/-!
# Challenge: `ZetaZeroes.v1`

**Generated file - do not edit.**  Regenerated by
`python scripts/ieantn.py gen-challenges` from `Conclusions.lean` and
`formalization.yaml`; CI diffs the two.

Each `sorry` below is deliberate and permanent: a challenge *states*, it does not prove.
How each conclusion is justified is recorded in `formalization.yaml`, not here.
-/

theorem ZetaZeroes.v1.challenge_no_nontrivial_zeroes_left : ZetaZeroes.v1.no_nontrivial_zeroes_left := by
  sorry

theorem ZetaZeroes.v1.challenge_zeroes_off_axis_in_strip : ZetaZeroes.v1.zeroes_off_axis_in_strip := by
  sorry

theorem ZetaZeroes.v1.challenge_finite_zeroes_on_compact : ZetaZeroes.v1.finite_zeroes_on_compact := by
  sorry

theorem ZetaZeroes.v1.challenge_exists_ordinate_free_height : ZetaZeroes.v1.exists_ordinate_free_height := by
  sorry

theorem ZetaZeroes.v1.challenge_zeta_eq_zeta1_div : ZetaZeroes.v1.zeta_eq_zeta1_div := by
  sorry

theorem ZetaZeroes.v1.challenge_zeta_eq_zero_iff_zeta1 : ZetaZeroes.v1.zeta_eq_zero_iff_zeta1 := by
  sorry
