name = "solution_GammaAsymptotics_v2"
defaultTargets = ["RealAsymptotic", "Periodic", "GaussSeries", "Recurrence", "ComplexToReal", "Oscillation", "RealIdentity", "Analytic", "Solution"]

[[require]]
name = "IEANTN"
path = "../.."

[[lean_lib]]
name = "RealAsymptotic"
roots = ["RealAsymptotic"]

[[lean_lib]]
name = "Periodic"
roots = ["Periodic"]

[[lean_lib]]
name = "GaussSeries"
roots = ["GaussSeries"]

[[lean_lib]]
name = "Recurrence"
roots = ["Recurrence"]

[[lean_lib]]
name = "ComplexToReal"
roots = ["ComplexToReal"]

[[lean_lib]]
name = "Oscillation"
roots = ["Oscillation"]

[[lean_lib]]
name = "RealIdentity"
roots = ["RealIdentity"]

[[lean_lib]]
name = "Analytic"
roots = ["Analytic"]

[[lean_lib]]
name = "Solution"
roots = ["Solution"]
